AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageUri:
    Type: String
  RoleArn:
    Type: String
  DBHost:
    Type: String

Resources:
  CrudLambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Role: !Ref RoleArn
      Timeout: 30
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_USER: admin
          DB_PASSWORD: password123
          DB_NAME: cruddb

Outputs:
  LambdaArn:
    Value: !GetAtt CrudLambda.Arn
