AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ecr.yaml

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iam.yaml

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yaml
